name = "chinesenamefinder"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# KV 命名空间配置（用于缓存）
[[kv_namespaces]]
binding = "CACHE_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# 默认变量（本地或未指定环境）
[vars]
APP_STAGE = "local"

# 环境变量（生产环境）
[env.production]
vars = { APP_STAGE = "production" }

[[env.production.kv_namespaces]]
binding = "CACHE_KV"
id = "your-kv-namespace-id"

# 环境变量（预览环境）
[env.preview]
vars = { APP_STAGE = "preview" }

[[env.preview.kv_namespaces]]
binding = "CACHE_KV"
id = "your-preview-kv-namespace-id"
