name = "chinesenamefinder"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# 使用 OpenNext Cloudflare 适配器的输出目录
# 注意：Cloudflare Pages 的 Build Output Directory 也需要设置为 .open-next
pages_build_output_dir = ".open-next"

# 强烈注意：不要在 wrangler.toml 中硬编码任何密钥！
# 请前往 Cloudflare Pages -> Settings -> Environment Variables
# 通过 UI 配置以下变量（Examples，仅供参考，不要提交真实值）：
# - APP_STAGE=production
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY
# - SUPABASE_SERVICE_ROLE_KEY (Secret)
# - OPENROUTER_API_KEY (Secret)
# - OPENROUTER_API_URL
# - STRIPE_SECRET_KEY (Secret)
# - STRIPE_WEBHOOK_SECRET (Secret)
# - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
#
# 如需为预览环境设置不同变量，请在 Cloudflare Pages 的 Preview 环境中配置。

# 如需在本地使用 wrangler 运行 Pages 预览，可在本地 shell 导出变量，
# 或使用 .env.local（切记不要提交到仓库）。
