name = "chinesenamefinder"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
# 使用 OpenNext Cloudflare 适配器的输出目录
pages_build_output_dir = ".vercel/output/static"

# 环境变量（生产环境）
[env.production]
vars = { APP_STAGE = "production" }

# 环境变量（预览环境）
[env.preview]
vars = { APP_STAGE = "preview" }
